/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    organigrama_person: OrganigramaPerson;
    official_bulletin: OfficialBulletin;
    commitment: Commitment;
    budget: Budget;
    tenders: Tender;
    participation: Participation;
    'public-works': PublicWork;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    organigrama_person: OrganigramaPersonSelect<false> | OrganigramaPersonSelect<true>;
    official_bulletin: OfficialBulletinSelect<false> | OfficialBulletinSelect<true>;
    commitment: CommitmentSelect<false> | CommitmentSelect<true>;
    budget: BudgetSelect<false> | BudgetSelect<true>;
    tenders: TendersSelect<false> | TendersSelect<true>;
    participation: ParticipationSelect<false> | ParticipationSelect<true>;
    'public-works': PublicWorksSelect<false> | PublicWorksSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-customization': SiteCustomization;
    'home-customization': HomeCustomization;
  };
  globalsSelect: {
    'site-customization': SiteCustomizationSelect<false> | SiteCustomizationSelect<true>;
    'home-customization': HomeCustomizationSelect<false> | HomeCustomizationSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Usuarios del sistema (admins, client-admins, editors).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Foto de perfil (png/jpg). Máx 2MB.
   */
  avatar?: (number | null) | Media;
  phone?: string | null;
  /**
   * Breve descripción / bio del usuario
   */
  bio?: string | null;
  /**
   * Rol del usuario. Solo un admin puede cambiar este campo.
   */
  role?: ('admin' | 'client-admin' | 'editor') | null;
  /**
   * Destildar para desactivar la cuenta sin borrarla.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    profile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organigrama_person".
 */
export interface OrganigramaPerson {
  id: number;
  fullName: string;
  role: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  cv?: (number | null) | Media;
  heroText?: string | null;
  subordinateAreas?:
    | {
        areaName?: string | null;
        responsibleName?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "official_bulletin".
 */
export interface OfficialBulletin {
  id: number;
  number: string;
  publishedDate: string;
  type?: ('disposiciones' | 'resoluciones' | 'ordenanzas') | null;
  heroText?: string | null;
  file: number | Media;
  isPublished: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Compromisos del municipio
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commitment".
 */
export interface Commitment {
  id: number;
  title: string;
  heroText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  status?: ('not-started' | 'in-progress' | 'completed') | null;
  percentageCompleted?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget".
 */
export interface Budget {
  id: number;
  title: string;
  description: string;
  heroText?: string | null;
  year: number;
  files: number | Media;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Licitaciones del municipio
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders".
 */
export interface Tender {
  id: number;
  pageText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedDate: string;
  title: string;
  object: string;
  officialBudget: string;
  deadlineRetiroPliego?: string | null;
  deadlineOfertas?: string | null;
  openingDate?: string | null;
  openingTime?: string | null;
  lugarApertura?: string | null;
  valorPliego?: string | null;
  fechaValorPliego?: string | null;
  lugarEntrega?: string | null;
  infoAdicional?: string | null;
  contactEmail?: string | null;
  attachedFile?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestión completa de Participación Ciudadana
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participation".
 */
export interface Participation {
  id: number;
  isConfig?: boolean | null;
  /**
   * Solo editable en el documento de configuración
   */
  heroText?: string | null;
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  enableSubmissions?: boolean | null;
  title?: string | null;
  fullName?: string | null;
  email?: string | null;
  projectArea?: ('educacion' | 'salud') | null;
  summary?: string | null;
  status?: ('pendiente' | 'en-revision' | 'aprobado' | 'rechazado') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-works".
 */
export interface PublicWork {
  id: number;
  title: string;
  description: string;
  contractor?: string | null;
  workType:
    | 'pavimento'
    | 'alumbrado'
    | 'red-de-agua'
    | 'red-de-cloacas'
    | 'edificio-publico'
    | 'parque-jardin'
    | 'plaza'
    | 'otro';
  location?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  segments?:
    | {
        street?: string | null;
        points?:
          | {
              latitude: number;
              longitude: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  photos?: (number | Media)[] | null;
  /**
   * Porcentaje de avance actual
   */
  progress: number;
  progressHistory?:
    | {
        date: string;
        progress: number;
        comment?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'organigrama_person';
        value: number | OrganigramaPerson;
      } | null)
    | ({
        relationTo: 'official_bulletin';
        value: number | OfficialBulletin;
      } | null)
    | ({
        relationTo: 'commitment';
        value: number | Commitment;
      } | null)
    | ({
        relationTo: 'budget';
        value: number | Budget;
      } | null)
    | ({
        relationTo: 'tenders';
        value: number | Tender;
      } | null)
    | ({
        relationTo: 'participation';
        value: number | Participation;
      } | null)
    | ({
        relationTo: 'public-works';
        value: number | PublicWork;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  avatar?: T;
  phone?: T;
  bio?: T;
  role?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        profile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organigrama_person_select".
 */
export interface OrganigramaPersonSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  bio?: T;
  photo?: T;
  cv?: T;
  heroText?: T;
  subordinateAreas?:
    | T
    | {
        areaName?: T;
        responsibleName?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "official_bulletin_select".
 */
export interface OfficialBulletinSelect<T extends boolean = true> {
  number?: T;
  publishedDate?: T;
  type?: T;
  heroText?: T;
  file?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commitment_select".
 */
export interface CommitmentSelect<T extends boolean = true> {
  title?: T;
  heroText?: T;
  summary?: T;
  image?: T;
  status?: T;
  percentageCompleted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget_select".
 */
export interface BudgetSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  heroText?: T;
  year?: T;
  files?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders_select".
 */
export interface TendersSelect<T extends boolean = true> {
  pageText?: T;
  publishedDate?: T;
  title?: T;
  object?: T;
  officialBudget?: T;
  deadlineRetiroPliego?: T;
  deadlineOfertas?: T;
  openingDate?: T;
  openingTime?: T;
  lugarApertura?: T;
  valorPliego?: T;
  fechaValorPliego?: T;
  lugarEntrega?: T;
  infoAdicional?: T;
  contactEmail?: T;
  attachedFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participation_select".
 */
export interface ParticipationSelect<T extends boolean = true> {
  isConfig?: T;
  heroText?: T;
  instructions?: T;
  enableSubmissions?: T;
  title?: T;
  fullName?: T;
  email?: T;
  projectArea?: T;
  summary?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-works_select".
 */
export interface PublicWorksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  contractor?: T;
  workType?: T;
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  segments?:
    | T
    | {
        street?: T;
        points?:
          | T
          | {
              latitude?: T;
              longitude?: T;
              id?: T;
            };
        id?: T;
      };
  photos?: T;
  progress?: T;
  progressHistory?:
    | T
    | {
        date?: T;
        progress?: T;
        comment?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-customization".
 */
export interface SiteCustomization {
  id: number;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-customization".
 */
export interface HomeCustomization {
  id: number;
  siteName: string;
  slogan?: string | null;
  description?: string | null;
  enabledSections?:
    | (
        | 'organigrama_person'
        | 'official_bulletin'
        | 'commitment'
        | 'budget'
        | 'tenders'
        | 'public-works'
        | 'participation'
      )[]
    | null;
  address?: string | null;
  phone?: string | null;
  contactEmail?: string | null;
  socialLinks?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-customization_select".
 */
export interface SiteCustomizationSelect<T extends boolean = true> {
  logo?: T;
  favicon?: T;
  primaryColor?: T;
  secondaryColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-customization_select".
 */
export interface HomeCustomizationSelect<T extends boolean = true> {
  siteName?: T;
  slogan?: T;
  description?: T;
  enabledSections?: T;
  address?: T;
  phone?: T;
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}